name: Build and run everything
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build-all-alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install bash
        run: apk add bash git
      - name: Silence some git warnings
        run: git config --global advice.detachedHead false
      - name: Install and build all benchmarks and allocators
        # dh: glibc-specific
        # gd: ?
        # hd: glibc-specific
        # mesh/nomesh: infinite loop?
        # sg: src/gnuwrapper.cpp:51:32: error: expected ')' before '__malloc_initialize_hook'
        # sm: ../src/supermalloc.h:10:31: error: expected initializer before '__THROW'
        # tbb: needs RTLD_DEEPBIND, but it doesn't exist on musl
        # tcg: installing bazel on alpine is awful
        run: ./build-bench-env.sh all no-dh no-hd no-tbb no-sm no-mesh no-nomesh no-tcg no-gd no-sg
      - name: Run everything.
        run: |
          cd out/bench
          # iso: too slow
          ../../bench.sh alla allt no-iso
  build-all-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Silence some git warnings
        run: git config --global advice.detachedHead false
      - name: Install and build all benchmarks and allocators
        # gd: infinite loop in the redis benchmark
        # sg: infinite loop in the redis benchmark
        run: ./build-bench-env.sh all no-lean no-gd no-sg
      - name: Run everything.
        run: |
          cd out/bench
          # iso: too slow
          ../../bench.sh alla allt no-iso
  build-all-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install git
        run: sudo dnf -y --quiet --nodocs install git
      - name: Silence some git warnings
        run: git config --global advice.detachedHead false
      - name: Install and build all benchmarks and allocators
        # gd: infinite loop in the redis benchmark
        # mesh/nomesh: error: '__malloc_hook' was not declared in this scope;
        # mi: error: '__malloc_hook' was not declared in this scope;
        # sg: src/gnuwrapper.cpp:55:23: error: '__malloc_hook' was not declared in this scope; did you mean 'my_malloc_hook'?
        run: ./build-bench-env.sh all no-lean no-mi no-mesh no-nomesh no-gd no-sg
      - name: Run everything.
        run: |
          cd out/bench
          # iso: too slow
          ../../bench.sh alla allt no-iso
  build-all-osx:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Silence some git warnings
        run: git config --global advice.detachedHead false
      - name: Install and build all benchmarks and allocators
        # ff: error: use of undeclared identifier 'MAP_POPULATE'
        # gd: so many errors
        run: ./build-bench-env.sh all no-lean no-gd no-ff
      - name: Run everything.
        run: |
          cd out/bench
          # iso: too slow
          ../../bench.sh alla allt no-iso
